#!/bin/bash

mysql -uroot clarity < sql/clarity_min3avo2.sql

sudo find  /var/lib/mysql/clarity -name "*.csv" -exec sudo rm {} \;
sudo php ./read.php

sudo find  /var/lib/mysql/clarity -name "*.csv" -exec sudo rm {} \;

sudo chown -R jw *