#!/bin/bash

mysql -uroot clarity < sql/clarity_min3avo.sql

find  /var/lib/mysql/clarity -name "*.csv" -exec sudo rm {} \;
php ./read.php

find  /var/lib/mysql/clarity -name "*.csv" -exec sudo rm {} \;

chown -R jw *