#!/bin/bash
D=$1
mysqldump -uroot --add-drop-table clarity > clarity_${D}.sql
mysqldump -uroot --add-drop-table --skip-opt clarity > clarity_${D}_noopt.sql
echo "clarity_${D}.sql" >lastsave
cat lastsave