#!/bin/bash
D=$1
mysqldump -uroot --add-drop-table clarity > sql/clarity_${D}.sql
mysqldump -uroot --add-drop-table --skip-opt clarity > sql/clarity_${D}_noopt.sql
echo "clarity_${D}.sql" >lastsave
cat lastsave