#!/bin/bash
D=$1
mysqldump -uroot --add-drop-table clarity > sql/clarity_${D}.sql
mysqldump -uroot --add-drop-table --skip-extended-insert clarity > sql/clarity_${D}_noopt.sql
echo "sql/clarity_${D}.sql" >lastsave
echo "sql/clarity_${D}_noopt.sql"
cat lastsave